//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DVDVideoSoft.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class CommonData {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CommonData() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DVDVideoSoft.Resources.CommonData", typeof(CommonData).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Above Normal.
        /// </summary>
        public static string AboveNormalPriority {
            get {
                return ResourceManager.GetString("AboveNormalPriority", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Speed up video encoding with {0} technology.
        /// </summary>
        public static string AccelerateVideoEncodingWithFmtString {
            get {
                return ResourceManager.GetString("AccelerateVideoEncodingWithFmtString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add program to Windows Explorer context menu.
        /// </summary>
        public static string AddProgrammToContextMenuWindows {
            get {
                return ResourceManager.GetString("AddProgrammToContextMenuWindows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add to the convert list of.
        /// </summary>
        public static string AddToConvertList {
            get {
                return ResourceManager.GetString("AddToConvertList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All DVDVideoSoft programs must be closed before the report is generated.\nClose {0} now and generate the report?.
        /// </summary>
        public static string AllDvsProgramsMustBeClosed {
            get {
                return ResourceManager.GetString("AllDvsProgramsMustBeClosed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I have already turned off AVG Accelerator.
        /// </summary>
        public static string AlreadyTurnedOffAVGAccelerator {
            get {
                return ResourceManager.GetString("AlreadyTurnedOffAVGAccelerator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to and.
        /// </summary>
        public static string And {
            get {
                return ResourceManager.GetString("And", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred.
        /// </summary>
        public static string AnErrorOccured {
            get {
                return ResourceManager.GetString("AnErrorOccured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A tag name cannot contain comma.
        /// </summary>
        public static string ATagCannotContain {
            get {
                return ResourceManager.GetString("ATagCannotContain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Audio.
        /// </summary>
        public static string Audio {
            get {
                return ResourceManager.GetString("Audio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quality.
        /// </summary>
        public static string AudioQuality {
            get {
                return ResourceManager.GetString("AudioQuality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to are available,.
        /// </summary>
        public static string Available {
            get {
                return ResourceManager.GetString("Available", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AVG Accelerator is running on your PC. Sometimes it freezes Internet connection.\n\nDVDVideoSoft tools use own acceleration and do not need AVG Accelerator. We recommend to turn it off.\n\nRead how to disable AVG Accelerator here:.
        /// </summary>
        public static string AVGIsRunningWarning {
            get {
                return ResourceManager.GetString("AVGIsRunningWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A file name cannot contain any of the following characters:.
        /// </summary>
        public static string BadCharacters {
            get {
                return ResourceManager.GetString("BadCharacters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Below Normal.
        /// </summary>
        public static string BelowNormalPriority {
            get {
                return ResourceManager.GetString("BelowNormalPriority", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Files and Folders:.
        /// </summary>
        public static string BrowseForFilesAndFolder_MainLabel {
            get {
                return ResourceManager.GetString("BrowseForFilesAndFolder_MainLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Include subfolders.
        /// </summary>
        public static string BrowseForFilesAndFolders_InclSub {
            get {
                return ResourceManager.GetString("BrowseForFilesAndFolders_InclSub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse files and folders.
        /// </summary>
        public static string BrowseForFilesAndFolders_Title {
            get {
                return ResourceManager.GetString("BrowseForFilesAndFolders_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buy Now.
        /// </summary>
        public static string BuyNow {
            get {
                return ResourceManager.GetString("BuyNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cancelled.
        /// </summary>
        public static string Cancelled {
            get {
                return ResourceManager.GetString("Cancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Canceling process....
        /// </summary>
        public static string CancelProcess {
            get {
                return ResourceManager.GetString("CancelProcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The program did not manage to access YouTube.
        /// </summary>
        public static string CannotAccessYouTube {
            get {
                return ResourceManager.GetString("CannotAccessYouTube", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot connect to the server.
        /// </summary>
        public static string CannotConnectToTheServer {
            get {
                return ResourceManager.GetString("CannotConnectToTheServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot download the codec pack.
        /// </summary>
        public static string CannotDownloadTheCodecPack {
            get {
                return ResourceManager.GetString("CannotDownloadTheCodecPack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The program cannot read this file. It is not a valid file or its format is not currently supported..
        /// </summary>
        public static string CannotReadFile {
            get {
                return ResourceManager.GetString("CannotReadFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The program does not manage to resolve this YouTube link. Do you want to find a solution?.
        /// </summary>
        public static string CannotResolveYouTubeLink {
            get {
                return ResourceManager.GetString("CannotResolveYouTubeLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot save video to the file:.
        /// </summary>
        public static string CannotSaveVideo {
            get {
                return ResourceManager.GetString("CannotSaveVideo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot find any tags for this file.
        /// </summary>
        public static string CantFindTags {
            get {
                return ResourceManager.GetString("CantFindTags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checking....
        /// </summary>
        public static string Checking {
            get {
                return ResourceManager.GetString("Checking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check your firewall, proxy or internet connection settings..
        /// </summary>
        public static string CheckInternetConnection {
            get {
                return ResourceManager.GetString("CheckInternetConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check preset parameters.
        /// </summary>
        public static string CheckPresetParameters {
            get {
                return ResourceManager.GetString("CheckPresetParameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clipboard is in use by other process, please try later..
        /// </summary>
        public static string ClipboardIsInUse {
            get {
                return ResourceManager.GetString("ClipboardIsInUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The codec pack has been downloaded and is ready to install. All DVDVideoSoft programs will be closed automatically..
        /// </summary>
        public static string CodecPackDownloadedAndReady {
            get {
                return ResourceManager.GetString("CodecPackDownloadedAndReady", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Codecs download.
        /// </summary>
        public static string CodecsDownload {
            get {
                return ResourceManager.GetString("CodecsDownload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comment.
        /// </summary>
        public static string Comment {
            get {
                return ResourceManager.GetString("Comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to completed.
        /// </summary>
        public static string Completed {
            get {
                return ResourceManager.GetString("Completed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completed.
        /// </summary>
        public static string Completed_U {
            get {
                return ResourceManager.GetString("Completed_U", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm.
        /// </summary>
        public static string Confirm {
            get {
                return ResourceManager.GetString("Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection error.
        /// </summary>
        public static string ConnectionError {
            get {
                return ResourceManager.GetString("ConnectionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue?.
        /// </summary>
        public static string Continue {
            get {
                return ResourceManager.GetString("Continue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conversion was completed successfully.
        /// </summary>
        public static string ConversionCompleteSuccessful {
            get {
                return ResourceManager.GetString("ConversionCompleteSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conversion error.
        /// </summary>
        public static string ConversionError {
            get {
                return ResourceManager.GetString("ConversionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conversion failed.
        /// </summary>
        public static string ConversionFailed {
            get {
                return ResourceManager.GetString("ConversionFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conversion progress.
        /// </summary>
        public static string ConversionProgress {
            get {
                return ResourceManager.GetString("ConversionProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Converted.
        /// </summary>
        public static string Converted {
            get {
                return ResourceManager.GetString("Converted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Converting.
        /// </summary>
        public static string Converting {
            get {
                return ResourceManager.GetString("Converting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Convert with.
        /// </summary>
        public static string ConvertWith {
            get {
                return ResourceManager.GetString("ConvertWith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy to Clipboard?.
        /// </summary>
        public static string CopyItToClipboard {
            get {
                return ResourceManager.GetString("CopyItToClipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create DVD.
        /// </summary>
        public static string CreateDVD {
            get {
                return ResourceManager.GetString("CreateDVD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create M3U playlist.
        /// </summary>
        public static string CreateM3Uplaylist {
            get {
                return ResourceManager.GetString("CreateM3Uplaylist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current:.
        /// </summary>
        public static string Current {
            get {
                return ResourceManager.GetString("Current", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detection.
        /// </summary>
        public static string Detection {
            get {
                return ResourceManager.GetString("Detection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot save file to the output folder. Please select another one..
        /// </summary>
        public static string DirectoryNotWritable {
            get {
                return ResourceManager.GetString("DirectoryNotWritable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disabling &apos;Cookies&apos; in browsers may prevent the program from working correctly.\n\nConsider to enable Cookies in.
        /// </summary>
        public static string DisabledCookies_EnableCookiesIn {
            get {
                return ResourceManager.GetString("DisabledCookies_EnableCookiesIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Don&apos;t ask again.
        /// </summary>
        public static string DontAskAgain {
            get {
                return ResourceManager.GetString("DontAskAgain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Don&apos;t ask again. (Enable this question in Options).
        /// </summary>
        public static string DontAskAgain_EnableInOptions {
            get {
                return ResourceManager.GetString("DontAskAgain_EnableInOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download failed.
        /// </summary>
        public static string DownloadFailed {
            get {
                return ResourceManager.GetString("DownloadFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloading.
        /// </summary>
        public static string Downloading {
            get {
                return ResourceManager.GetString("Downloading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloading is completed.
        /// </summary>
        public static string DownloadingCompleted {
            get {
                return ResourceManager.GetString("DownloadingCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloading was completed successfully.
        /// </summary>
        public static string DownloadingCompleteSuccesful {
            get {
                return ResourceManager.GetString("DownloadingCompleteSuccesful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloading in progress, please wait....
        /// </summary>
        public static string DownloadingInProgress {
            get {
                return ResourceManager.GetString("DownloadingInProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drag and drop files here.
        /// </summary>
        public static string DragAndDropFilesHere {
            get {
                return ResourceManager.GetString("DragAndDropFilesHere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DVD.
        /// </summary>
        public static string Dvd {
            get {
                return ResourceManager.GetString("Dvd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DVD DL.
        /// </summary>
        public static string DvdDl {
            get {
                return ResourceManager.GetString("DvdDl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating DVD video....
        /// </summary>
        public static string DVDVideoCreation {
            get {
                return ResourceManager.GetString("DVDVideoCreation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Economy.
        /// </summary>
        public static string Economy {
            get {
                return ResourceManager.GetString("Economy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enqueued.
        /// </summary>
        public static string Enqueued {
            get {
                return ResourceManager.GetString("Enqueued", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the verification code in your browser and restart the program. Open the browser now?.
        /// </summary>
        public static string EnterVerificationCodeAndRestart {
            get {
                return ResourceManager.GetString("EnterVerificationCodeAndRestart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estimated output dvd size (+/- 10%).
        /// </summary>
        public static string EstimatedDvdSize {
            get {
                return ResourceManager.GetString("EstimatedDvdSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed.
        /// </summary>
        public static string Failed {
            get {
                return ResourceManager.GetString("Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to connect to the Internet.
        /// </summary>
        public static string FailedToConnectToTheInternet {
            get {
                return ResourceManager.GetString("FailedToConnectToTheInternet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to get response from the registration server.
        /// </summary>
        public static string FailedToGetResponseFromServer {
            get {
                return ResourceManager.GetString("FailedToGetResponseFromServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to save license file.
        /// </summary>
        public static string FailedToSaveLicenseFile {
            get {
                return ResourceManager.GetString("FailedToSaveLicenseFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This file format is not supported.
        /// </summary>
        public static string FileFormatNotSupported {
            get {
                return ResourceManager.GetString("FileFormatNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to file(s) is failed..
        /// </summary>
        public static string FileIsFailed {
            get {
                return ResourceManager.GetString("FileIsFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot locate any file from the CUE list.
        /// </summary>
        public static string FilesNotFound {
            get {
                return ResourceManager.GetString("FilesNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Some files were not opened.
        /// </summary>
        public static string FilesNotOpened {
            get {
                return ResourceManager.GetString("FilesNotOpened", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file is too large.
        /// </summary>
        public static string FileTooLarge {
            get {
                return ResourceManager.GetString("FileTooLarge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uploading file....
        /// </summary>
        public static string FileUploading {
            get {
                return ResourceManager.GetString("FileUploading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flash player.
        /// </summary>
        public static string FlashPlayer {
            get {
                return ResourceManager.GetString("FlashPlayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Formats.
        /// </summary>
        public static string Formats {
            get {
                return ResourceManager.GetString("Formats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate Report.
        /// </summary>
        public static string GenerateReport {
            get {
                return ResourceManager.GetString("GenerateReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get Rocket Subscription.
        /// </summary>
        public static string GetRocketSubsctiption {
            get {
                return ResourceManager.GetString("GetRocketSubsctiption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go to {0}.
        /// </summary>
        public static string GoTo {
            get {
                return ResourceManager.GetString("GoTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to High Definition Video.
        /// </summary>
        public static string HD_Video {
            get {
                return ResourceManager.GetString("HD_Video", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to High.
        /// </summary>
        public static string High {
            get {
                return ResourceManager.GetString("High", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to High priority.
        /// </summary>
        public static string HighPriority {
            get {
                return ResourceManager.GetString("HighPriority", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to High Quality Video.
        /// </summary>
        public static string HQ_Video {
            get {
                return ResourceManager.GetString("HQ_Video", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information.
        /// </summary>
        public static string Information {
            get {
                return ResourceManager.GetString("Information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid login/password.
        /// </summary>
        public static string InvalidLoginPassword {
            get {
                return ResourceManager.GetString("InvalidLoginPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong subscription key, please try again.
        /// </summary>
        public static string InvalidSubscriptionKey {
            get {
                return ResourceManager.GetString("InvalidSubscriptionKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Just send the file &quot;{0}&quot;\nto DVDVideoSoft support team.
        /// </summary>
        public static string JustSendTheLogs_template {
            get {
                return ResourceManager.GetString("JustSendTheLogs_template", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Learn more.
        /// </summary>
        public static string LearnMore {
            get {
                return ResourceManager.GetString("LearnMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to License file corrupted.
        /// </summary>
        public static string LicenseFileCorrupted {
            get {
                return ResourceManager.GetString("LicenseFileCorrupted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to License file not found.
        /// </summary>
        public static string LicenseFileNotFound {
            get {
                return ResourceManager.GetString("LicenseFileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to License has expired.
        /// </summary>
        public static string LicenseHasExpired {
            get {
                return ResourceManager.GetString("LicenseHasExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Link does not contain video.
        /// </summary>
        public static string LinkNotContainVideo {
            get {
                return ResourceManager.GetString("LinkNotContainVideo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The list is not loaded.
        /// </summary>
        public static string ListNotLoaded {
            get {
                return ResourceManager.GetString("ListNotLoaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The list is not saved..
        /// </summary>
        public static string ListNotSaved {
            get {
                return ResourceManager.GetString("ListNotSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Low priority.
        /// </summary>
        public static string LowPriority {
            get {
                return ResourceManager.GetString("LowPriority", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manual proxy configuration.
        /// </summary>
        public static string ManualProxy {
            get {
                return ResourceManager.GetString("ManualProxy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mono.
        /// </summary>
        public static string Mono {
            get {
                return ResourceManager.GetString("Mono", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The application requires Microsoft .NET Framework 3.5. Do you want to install it now?.
        /// </summary>
        public static string NetFx35Install {
            get {
                return ResourceManager.GetString("NetFx35Install", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New folder.
        /// </summary>
        public static string NewFolder {
            get {
                return ResourceManager.GetString("NewFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New version is available.
        /// </summary>
        public static string NewVersionIsAvailable {
            get {
                return ResourceManager.GetString("NewVersionIsAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Connection. Check Internet connection..
        /// </summary>
        public static string NoConnection {
            get {
                return ResourceManager.GetString("NoConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No proxy.
        /// </summary>
        public static string NoProxy {
            get {
                return ResourceManager.GetString("NoProxy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Normal priority.
        /// </summary>
        public static string NormalPriority {
            get {
                return ResourceManager.GetString("NormalPriority", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is not enough space on the disc.
        /// </summary>
        public static string NotEnoughSpace {
            get {
                return ResourceManager.GetString("NotEnoughSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No URL to download from!.
        /// </summary>
        public static string NotURLToDownloadVideoFrom {
            get {
                return ResourceManager.GetString("NotURLToDownloadVideoFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is not a YouTube link.
        /// </summary>
        public static string NotYouTubeLink {
            get {
                return ResourceManager.GetString("NotYouTubeLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No video data.
        /// </summary>
        public static string NoVideoData {
            get {
                return ResourceManager.GetString("NoVideoData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Normal Quality Video.
        /// </summary>
        public static string NQ_Video {
            get {
                return ResourceManager.GetString("NQ_Video", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Occupied Space:.
        /// </summary>
        public static string OccupiedSpace {
            get {
                return ResourceManager.GetString("OccupiedSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to of.
        /// </summary>
        public static string Of {
            get {
                return ResourceManager.GetString("Of", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ooops, you have not added any files.
        /// </summary>
        public static string OoopsNoFiles {
            get {
                return ResourceManager.GetString("OoopsNoFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image files.
        /// </summary>
        public static string OpenDlgImageFilter {
            get {
                return ResourceManager.GetString("OpenDlgImageFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open in External Player.
        /// </summary>
        public static string OpenInExternalPlayer {
            get {
                return ResourceManager.GetString("OpenInExternalPlayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Log Folder.
        /// </summary>
        public static string OpenLogFolder {
            get {
                return ResourceManager.GetString("OpenLogFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options.
        /// </summary>
        public static string Options {
            get {
                return ResourceManager.GetString("Options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Original.
        /// </summary>
        public static string Original {
            get {
                return ResourceManager.GetString("Original", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bitrate, Sample Rate, Channel(s) as in Input File.
        /// </summary>
        public static string OriginalQualityDescription {
            get {
                return ResourceManager.GetString("OriginalQualityDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Original_Video_Name.
        /// </summary>
        public static string OriginalVideoName {
            get {
                return ResourceManager.GetString("OriginalVideoName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Original YouTube.
        /// </summary>
        public static string OriginalYoutube {
            get {
                return ResourceManager.GetString("OriginalYoutube", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The output file already exists. Replace it?.
        /// </summary>
        public static string OutputFileAlreadyExists {
            get {
                return ResourceManager.GetString("OutputFileAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output folder....
        /// </summary>
        public static string OutputFolder {
            get {
                return ResourceManager.GetString("OutputFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The output folder does not exist.
        /// </summary>
        public static string OutputFolderNotExist {
            get {
                return ResourceManager.GetString("OutputFolderNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The output path is empty.
        /// </summary>
        public static string OutputPathEmpty {
            get {
                return ResourceManager.GetString("OutputPathEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paused.
        /// </summary>
        public static string Paused {
            get {
                return ResourceManager.GetString("Paused", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play.
        /// </summary>
        public static string Play {
            get {
                return ResourceManager.GetString("Play", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play Downloaded Audio File.
        /// </summary>
        public static string PlayDownloadedAudioFile {
            get {
                return ResourceManager.GetString("PlayDownloadedAudioFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play Downloaded Video.
        /// </summary>
        public static string PlayDownloadedVideo {
            get {
                return ResourceManager.GetString("PlayDownloadedVideo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player....
        /// </summary>
        public static string Player {
            get {
                return ResourceManager.GetString("Player", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player color:.
        /// </summary>
        public static string PlayerColor {
            get {
                return ResourceManager.GetString("PlayerColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player:.
        /// </summary>
        public static string PlayerImageLabel {
            get {
                return ResourceManager.GetString("PlayerImageLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player type:.
        /// </summary>
        public static string PlayerType {
            get {
                return ResourceManager.GetString("PlayerType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Playlist.
        /// </summary>
        public static string Playlist {
            get {
                return ResourceManager.GetString("Playlist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play / Stop.
        /// </summary>
        public static string PlayStop {
            get {
                return ResourceManager.GetString("PlayStop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please add audio files.
        /// </summary>
        public static string PleaseAddAudioFiles {
            get {
                return ResourceManager.GetString("PleaseAddAudioFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter at least one tag for your video.
        /// </summary>
        public static string PleaseEnterTag {
            get {
                return ResourceManager.GetString("PleaseEnterTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please install the latest version directly from our website:.
        /// </summary>
        public static string PleaseInstallTheLatest {
            get {
                return ResourceManager.GetString("PleaseInstallTheLatest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please reproduce the problem and then run System Report again.
        /// </summary>
        public static string PleaseReproduceTheProblem {
            get {
                return ResourceManager.GetString("PleaseReproduceTheProblem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preset.
        /// </summary>
        public static string Preset {
            get {
                return ResourceManager.GetString("Preset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preset.
        /// </summary>
        public static string Presets {
            get {
                return ResourceManager.GetString("Presets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Private.
        /// </summary>
        public static string Private {
            get {
                return ResourceManager.GetString("Private", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Process is completed.
        /// </summary>
        public static string ProcessComplete {
            get {
                return ResourceManager.GetString("ProcessComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Process was completed successfully.
        /// </summary>
        public static string ProcessCompletedSuccessfully {
            get {
                return ResourceManager.GetString("ProcessCompletedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processing.
        /// </summary>
        public static string Processing {
            get {
                return ResourceManager.GetString("Processing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File conversion....
        /// </summary>
        public static string ProcessingFile {
            get {
                return ResourceManager.GetString("ProcessingFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Process is stopped.
        /// </summary>
        public static string ProcessStopped {
            get {
                return ResourceManager.GetString("ProcessStopped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Progress.
        /// </summary>
        public static string Progress {
            get {
                return ResourceManager.GetString("Progress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Public.
        /// </summary>
        public static string Public {
            get {
                return ResourceManager.GetString("Public", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quality.
        /// </summary>
        public static string Quality {
            get {
                return ResourceManager.GetString("Quality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to get response from the registration server.
        /// </summary>
        public static string ReadHttpResponseFailed {
            get {
                return ResourceManager.GetString("ReadHttpResponseFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ready for download.
        /// </summary>
        public static string ReadyForDownload {
            get {
                return ResourceManager.GetString("ReadyForDownload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registration.
        /// </summary>
        public static string Registration {
            get {
                return ResourceManager.GetString("Registration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registration failed.
        /// </summary>
        public static string RegistrationFailed {
            get {
                return ResourceManager.GetString("RegistrationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registration is complete.
        /// </summary>
        public static string RegistrationIsComplete {
            get {
                return ResourceManager.GetString("RegistrationIsComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reinstall the program.
        /// </summary>
        public static string ReinstallProgramm {
            get {
                return ResourceManager.GetString("ReinstallProgramm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rename.
        /// </summary>
        public static string Rename {
            get {
                return ResourceManager.GetString("Rename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report has been generated successfully.\nOpen the folder with archived logs now?.
        /// </summary>
        public static string ReportHasBeenGenerated {
            get {
                return ResourceManager.GetString("ReportHasBeenGenerated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to are required..
        /// </summary>
        public static string Required {
            get {
                return ResourceManager.GetString("Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The program cannot continue working as a required module is missing.
        /// </summary>
        public static string RequiredModuleMissing {
            get {
                return ResourceManager.GetString("RequiredModuleMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This setup requires Microsoft Image Mastering API (IMAPI). Please download and install it, then run the setup again. Do you want to download IMAPI now?.
        /// </summary>
        public static string RequiresImapi {
            get {
                return ResourceManager.GetString("RequiresImapi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restart the program now?.
        /// </summary>
        public static string RestartQuestion {
            get {
                return ResourceManager.GetString("RestartQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rocket Subscription features are activated.
        /// </summary>
        public static string RocketSubscriptionFeaturesAreActivated {
            get {
                return ResourceManager.GetString("RocketSubscriptionFeaturesAreActivated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Same as input.
        /// </summary>
        public static string SameAsInput {
            get {
                return ResourceManager.GetString("SameAsInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save video.
        /// </summary>
        public static string SaveVideo {
            get {
                return ResourceManager.GetString("SaveVideo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please, select a file.
        /// </summary>
        public static string SelectFile {
            get {
                return ResourceManager.GetString("SelectFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setup.
        /// </summary>
        public static string Setup {
            get {
                return ResourceManager.GetString("Setup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setup in progress, please wait....
        /// </summary>
        public static string SetupInProgress {
            get {
                return ResourceManager.GetString("SetupInProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show an HTML Example File After Conversion.
        /// </summary>
        public static string ShowAnHTMLExampleFileAfterConversion {
            get {
                return ResourceManager.GetString("ShowAnHTMLExampleFileAfterConversion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show in folder.
        /// </summary>
        public static string ShowInFolder {
            get {
                return ResourceManager.GetString("ShowInFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Subscription Request Code.
        /// </summary>
        public static string ShowSubscriptionRequestCode {
            get {
                return ResourceManager.GetString("ShowSubscriptionRequestCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your computer will shut down in {0} sec.
        /// </summary>
        public static string ShutDownWarning {
            get {
                return ResourceManager.GetString("ShutDownWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Some changes require that you restart the program.
        ///Proceed?.
        /// </summary>
        public static string SomeChangesRequireRestart {
            get {
                return ResourceManager.GetString("SomeChangesRequireRestart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Some codecs are missing.
        /// </summary>
        public static string SomeCodecsAreMissing {
            get {
                return ResourceManager.GetString("SomeCodecsAreMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Some codecs are missing, they will be downloaded. Would you like to continue?.
        /// </summary>
        public static string SomeCodecsAreMissingTheyWillBeDownloaded {
            get {
                return ResourceManager.GetString("SomeCodecsAreMissingTheyWillBeDownloaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Some files were not processed.
        /// </summary>
        public static string SomeFilesWereNotProcessed {
            get {
                return ResourceManager.GetString("SomeFilesWereNotProcessed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The program did not download some links.
        /// </summary>
        public static string SomeLinksNotDownloaded {
            get {
                return ResourceManager.GetString("SomeLinksNotDownloaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Standard.
        /// </summary>
        public static string Standard {
            get {
                return ResourceManager.GetString("Standard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stereo.
        /// </summary>
        public static string Stereo {
            get {
                return ResourceManager.GetString("Stereo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop.
        /// </summary>
        public static string Stop {
            get {
                return ResourceManager.GetString("Stop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subscription request code:.
        /// </summary>
        public static string SubscriptionRequestCode {
            get {
                return ResourceManager.GetString("SubscriptionRequestCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subtitles.
        /// </summary>
        public static string Subtitles {
            get {
                return ResourceManager.GetString("Subtitles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use system proxy settings.
        /// </summary>
        public static string SystemProxy {
            get {
                return ResourceManager.GetString("SystemProxy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hints for tag creation:.
        /// </summary>
        public static string TagCreationHints {
            get {
                return ResourceManager.GetString("TagCreationHints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tag length cannot be more than 30 characters.
        /// </summary>
        public static string TagLengthCannotBe {
            get {
                return ResourceManager.GetString("TagLengthCannotBe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thank you for registering.
        /// </summary>
        public static string ThankYouForRegistering {
            get {
                return ResourceManager.GetString("ThankYouForRegistering", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The field cannot be blank.
        /// </summary>
        public static string TheFieldCannotBeBlank {
            get {
                return ResourceManager.GetString("TheFieldCannotBeBlank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The logging level will be set to TRACE. Continue?.
        /// </summary>
        public static string TheLoggingLevelWillBeSetToTrace {
            get {
                return ResourceManager.GetString("TheLoggingLevelWillBeSetToTrace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is a new version available. Do you want to download and install it now?.
        /// </summary>
        public static string ThereIsNewVersion {
            get {
                return ResourceManager.GetString("ThereIsNewVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This machine is not registered for this subscription.
        /// </summary>
        public static string ThisMachineIsNotRegistered {
            get {
                return ResourceManager.GetString("ThisMachineIsNotRegistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This video requires age verification on YouTube.\nPlease check &apos;Use Cookies&apos; in Options.\n
        ///Go to Options now?.
        /// </summary>
        public static string ThisVideoRequiresVerificationQuestion {
            get {
                return ResourceManager.GetString("ThisVideoRequiresVerificationQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This video requires age verification on YouTube so use of cookies has to be allowed. Go to:\nOptions =&gt; General =&gt; Use cookies.
        /// </summary>
        public static string ThisVideoRequiresVerificationSo {
            get {
                return ResourceManager.GetString("ThisVideoRequiresVerificationSo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total:.
        /// </summary>
        public static string Total {
            get {
                return ResourceManager.GetString("Total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Duration.
        /// </summary>
        public static string TotalDuration {
            get {
                return ResourceManager.GetString("TotalDuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to create a file on a CD/DVD disc..
        /// </summary>
        public static string UnableCreateOnCD {
            get {
                return ResourceManager.GetString("UnableCreateOnCD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsupported codec.
        /// </summary>
        public static string UnsupportedCodec {
            get {
                return ResourceManager.GetString("UnsupportedCodec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsupported file format.
        /// </summary>
        public static string UnsupportedFileFormat {
            get {
                return ResourceManager.GetString("UnsupportedFileFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to upload failed.
        /// </summary>
        public static string UploadFailed {
            get {
                return ResourceManager.GetString("UploadFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uploading....
        /// </summary>
        public static string Uploading {
            get {
                return ResourceManager.GetString("Uploading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Up to date.
        /// </summary>
        public static string UpToDate {
            get {
                return ResourceManager.GetString("UpToDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This URL does not contain YouTube video.
        /// </summary>
        public static string URLNotContainYTVideos {
            get {
                return ResourceManager.GetString("URLNotContainYTVideos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your version is up to date..
        /// </summary>
        public static string VersionIsUpToDate {
            get {
                return ResourceManager.GetString("VersionIsUpToDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Video.
        /// </summary>
        public static string Video {
            get {
                return ResourceManager.GetString("Video", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This video is already in the download list..
        /// </summary>
        public static string VideoAlreadyInList {
            get {
                return ResourceManager.GetString("VideoAlreadyInList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Video downloading....
        /// </summary>
        public static string VideoDownloading {
            get {
                return ResourceManager.GetString("VideoDownloading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File size or video duration exceeds allowed limits.
        /// </summary>
        public static string VideoFileSizeExceedsLimits {
            get {
                return ResourceManager.GetString("VideoFileSizeExceedsLimits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This video may be part of a playlist. Would you like to try to download the whole playlist?.
        /// </summary>
        public static string VideoMaybePartOfPlaylist {
            get {
                return ResourceManager.GetString("VideoMaybePartOfPlaylist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to videos.
        /// </summary>
        public static string Videos {
            get {
                return ResourceManager.GetString("Videos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to find a solution?.
        /// </summary>
        public static string WantSolution {
            get {
                return ResourceManager.GetString("WantSolution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        public static string Warning {
            get {
                return ResourceManager.GetString("Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong subscription key, please try again.
        /// </summary>
        public static string WrongSubscriptionKey {
            get {
                return ResourceManager.GetString("WrongSubscriptionKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Each tag must be at least two letters and/or numbers..
        /// </summary>
        public static string WrongTag {
            get {
                return ResourceManager.GetString("WrongTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to year.
        /// </summary>
        public static string Year {
            get {
                return ResourceManager.GetString("Year", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
