//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DVDVideoSoft.Controls.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DVDVideoSoft.Controls.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static System.Drawing.Bitmap Back_s {
            get {
                object obj = ResourceManager.GetObject("Back_s", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Back_s_new {
            get {
                object obj = ResourceManager.GetObject("Back_s_new", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap CancelledPicto {
            get {
                object obj = ResourceManager.GetObject("CancelledPicto", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap CancelledPicto_s {
            get {
                object obj = ResourceManager.GetObject("CancelledPicto_s", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap CheckAnimation {
            get {
                object obj = ResourceManager.GetObject("CheckAnimation", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap CheckAnimation_s {
            get {
                object obj = ResourceManager.GetObject("CheckAnimation_s", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap CheckingAnim {
            get {
                object obj = ResourceManager.GetObject("CheckingAnim", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap CheckingAnim_s {
            get {
                object obj = ResourceManager.GetObject("CheckingAnim_s", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ConvertingPicto {
            get {
                object obj = ResourceManager.GetObject("ConvertingPicto", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ConvertingPicto_s {
            get {
                object obj = ResourceManager.GetObject("ConvertingPicto_s", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap DiscSizeBar_back {
            get {
                object obj = ResourceManager.GetObject("DiscSizeBar_back", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap DownloadCompletePicto {
            get {
                object obj = ResourceManager.GetObject("DownloadCompletePicto", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap DownloadCompletePicto_s {
            get {
                object obj = ResourceManager.GetObject("DownloadCompletePicto_s", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap DownloadingPicto {
            get {
                object obj = ResourceManager.GetObject("DownloadingPicto", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap DownloadingPicto_s {
            get {
                object obj = ResourceManager.GetObject("DownloadingPicto_s", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap EnqueuedPicto {
            get {
                object obj = ResourceManager.GetObject("EnqueuedPicto", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap EnqueuedPicto_s {
            get {
                object obj = ResourceManager.GetObject("EnqueuedPicto_s", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap HistoryBack_s {
            get {
                object obj = ResourceManager.GetObject("HistoryBack_s", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap LearnMore_down {
            get {
                object obj = ResourceManager.GetObject("LearnMore_down", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap LearnMore_down_s {
            get {
                object obj = ResourceManager.GetObject("LearnMore_down_s", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap LearnMore_norm {
            get {
                object obj = ResourceManager.GetObject("LearnMore_norm", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap LearnMore_norm_s {
            get {
                object obj = ResourceManager.GetObject("LearnMore_norm_s", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap LearnMore_over {
            get {
                object obj = ResourceManager.GetObject("LearnMore_over", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap LearnMore_over_s {
            get {
                object obj = ResourceManager.GetObject("LearnMore_over_s", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap LearnMore_over1 {
            get {
                object obj = ResourceManager.GetObject("LearnMore_over1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap NoImage {
            get {
                object obj = ResourceManager.GetObject("NoImage", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap OpenPlaylist_down_new {
            get {
                object obj = ResourceManager.GetObject("OpenPlaylist_down_new", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap OpenPlaylist_norm_new {
            get {
                object obj = ResourceManager.GetObject("OpenPlaylist_norm_new", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap OutputFolder_down {
            get {
                object obj = ResourceManager.GetObject("OutputFolder_down", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap OutputFolder_down_s {
            get {
                object obj = ResourceManager.GetObject("OutputFolder_down_s", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap OutputFolder_norm {
            get {
                object obj = ResourceManager.GetObject("OutputFolder_norm", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap OutputFolder_norm_s {
            get {
                object obj = ResourceManager.GetObject("OutputFolder_norm_s", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap OutputFolder_over {
            get {
                object obj = ResourceManager.GetObject("OutputFolder_over", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap OutputFolder_over_s {
            get {
                object obj = ResourceManager.GetObject("OutputFolder_over_s", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Pause_down {
            get {
                object obj = ResourceManager.GetObject("Pause_down", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Pause_down_new {
            get {
                object obj = ResourceManager.GetObject("Pause_down_new", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Pause_down_s {
            get {
                object obj = ResourceManager.GetObject("Pause_down_s", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Pause_down_s_new {
            get {
                object obj = ResourceManager.GetObject("Pause_down_s_new", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Pause_norm {
            get {
                object obj = ResourceManager.GetObject("Pause_norm", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Pause_norm_new {
            get {
                object obj = ResourceManager.GetObject("Pause_norm_new", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Pause_norm_s {
            get {
                object obj = ResourceManager.GetObject("Pause_norm_s", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Pause_norm_s_new {
            get {
                object obj = ResourceManager.GetObject("Pause_norm_s_new", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Pause_over {
            get {
                object obj = ResourceManager.GetObject("Pause_over", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Pause_over_new {
            get {
                object obj = ResourceManager.GetObject("Pause_over_new", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Pause_over_s {
            get {
                object obj = ResourceManager.GetObject("Pause_over_s", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Pause_over_s_new {
            get {
                object obj = ResourceManager.GetObject("Pause_over_s_new", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap PausedPicto {
            get {
                object obj = ResourceManager.GetObject("PausedPicto", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap PausedPicto_s {
            get {
                object obj = ResourceManager.GetObject("PausedPicto_s", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Play_down_new {
            get {
                object obj = ResourceManager.GetObject("Play_down_new", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Play_norm_new {
            get {
                object obj = ResourceManager.GetObject("Play_norm_new", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Playlist {
            get {
                object obj = ResourceManager.GetObject("Playlist", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Playlist_new {
            get {
                object obj = ResourceManager.GetObject("Playlist_new", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ProcessingAnimation {
            get {
                object obj = ResourceManager.GetObject("ProcessingAnimation", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ProcessingAnimation_s {
            get {
                object obj = ResourceManager.GetObject("ProcessingAnimation_s", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ReadyToDownloadPicto {
            get {
                object obj = ResourceManager.GetObject("ReadyToDownloadPicto", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ReadyToDownloadPicto_s {
            get {
                object obj = ResourceManager.GetObject("ReadyToDownloadPicto_s", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap remove_btn_norm {
            get {
                object obj = ResourceManager.GetObject("remove_btn_norm", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Remove_down {
            get {
                object obj = ResourceManager.GetObject("Remove_down", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Remove_down_new {
            get {
                object obj = ResourceManager.GetObject("Remove_down_new", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Remove_down_s {
            get {
                object obj = ResourceManager.GetObject("Remove_down_s", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Remove_down_s_new {
            get {
                object obj = ResourceManager.GetObject("Remove_down_s_new", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Remove_norm {
            get {
                object obj = ResourceManager.GetObject("Remove_norm", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Remove_norm_new {
            get {
                object obj = ResourceManager.GetObject("Remove_norm_new", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Remove_norm_s {
            get {
                object obj = ResourceManager.GetObject("Remove_norm_s", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Remove_norm_s_new {
            get {
                object obj = ResourceManager.GetObject("Remove_norm_s_new", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Remove_over {
            get {
                object obj = ResourceManager.GetObject("Remove_over", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Remove_over_new {
            get {
                object obj = ResourceManager.GetObject("Remove_over_new", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Remove_over_s {
            get {
                object obj = ResourceManager.GetObject("Remove_over_s", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Remove_over_s_new {
            get {
                object obj = ResourceManager.GetObject("Remove_over_s_new", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap RowBack_s {
            get {
                object obj = ResourceManager.GetObject("RowBack_s", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ScrollDown {
            get {
                object obj = ResourceManager.GetObject("ScrollDown", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ScrollUp {
            get {
                object obj = ResourceManager.GetObject("ScrollUp", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap search {
            get {
                object obj = ResourceManager.GetObject("search", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap SingleVideo {
            get {
                object obj = ResourceManager.GetObject("SingleVideo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap SingleVideo_new {
            get {
                object obj = ResourceManager.GetObject("SingleVideo_new", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Start_down {
            get {
                object obj = ResourceManager.GetObject("Start_down", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Start_down_new {
            get {
                object obj = ResourceManager.GetObject("Start_down_new", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Start_down_s {
            get {
                object obj = ResourceManager.GetObject("Start_down_s", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Start_down_s_new {
            get {
                object obj = ResourceManager.GetObject("Start_down_s_new", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Start_norm {
            get {
                object obj = ResourceManager.GetObject("Start_norm", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Start_norm_new {
            get {
                object obj = ResourceManager.GetObject("Start_norm_new", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Start_norm_s {
            get {
                object obj = ResourceManager.GetObject("Start_norm_s", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Start_norm_s_new {
            get {
                object obj = ResourceManager.GetObject("Start_norm_s_new", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Start_over {
            get {
                object obj = ResourceManager.GetObject("Start_over", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Start_over_new {
            get {
                object obj = ResourceManager.GetObject("Start_over_new", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Start_over_s {
            get {
                object obj = ResourceManager.GetObject("Start_over_s", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Start_over_s_new {
            get {
                object obj = ResourceManager.GetObject("Start_over_s_new", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Stop_down {
            get {
                object obj = ResourceManager.GetObject("Stop_down", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Stop_down_new {
            get {
                object obj = ResourceManager.GetObject("Stop_down_new", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Stop_down_s {
            get {
                object obj = ResourceManager.GetObject("Stop_down_s", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Stop_norm {
            get {
                object obj = ResourceManager.GetObject("Stop_norm", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Stop_norm_new {
            get {
                object obj = ResourceManager.GetObject("Stop_norm_new", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Stop_norm_s {
            get {
                object obj = ResourceManager.GetObject("Stop_norm_s", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Stop_norm_s_new {
            get {
                object obj = ResourceManager.GetObject("Stop_norm_s_new", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Stop_over {
            get {
                object obj = ResourceManager.GetObject("Stop_over", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Stop_over_new {
            get {
                object obj = ResourceManager.GetObject("Stop_over_new", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Stop_over_s {
            get {
                object obj = ResourceManager.GetObject("Stop_over_s", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ThumbBottom {
            get {
                object obj = ResourceManager.GetObject("ThumbBottom", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ThumbMiddle {
            get {
                object obj = ResourceManager.GetObject("ThumbMiddle", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ThumbSpanBottom {
            get {
                object obj = ResourceManager.GetObject("ThumbSpanBottom", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ThumbSpanTop {
            get {
                object obj = ResourceManager.GetObject("ThumbSpanTop", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ThumbTop {
            get {
                object obj = ResourceManager.GetObject("ThumbTop", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
